### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by kalev** [fedora-infra/packagedb-cli#34]
I'm filing it against pkgdb-cli, but I think the error is actually on the server side.

```
$ pkgdb-cli update --approve adwaita-icon-theme commit group::gnome-sig all
FAS password for user kalev: 
Error: 'NoneType' object has no attribute 'get'
ERROR:root:Generic error catched:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pkgdb2client/cli.py", line 816, in main
    arg.func(arg)
  File "/usr/lib/python2.7/site-packages/pkgdb2client/cli.py", line 738, in do_update
    for msg in output.get('messages', []):
AttributeError: 'NoneType' object has no attribute 'get'
```

This is with packagedb-cli-2.8.2-1.fc22.noarch

**Comment by ralphbean** [comment]
There's likely an error server-side, but pkgdb cli should probably anticipate this ``output == None`` scenario and print something more meaningful.
