### ISSUE TITLE
setting different bzurl results in traceback

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/packagedb-cli#89]
```bash
~❯ pkgdb-admin --user ralph --pkgdburl https://admin.stg.fedoraproject.org/pkgdb --bzurl https://partner-bugzilla.redhat.com process 1457
Traceback (most recent call last):
  File "/usr/bin/pkgdb-admin", line 9, in <module>
    load_entry_point('packagedb-cli==2.12', 'console_scripts', 'pkgdb-admin')()
  File "/usr/lib/python2.7/site-packages/pkgdb2client/admin.py", line 504, in main
    utils.BZCLIENT.url = arg.bzurl
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by pypingou** [comment]
nice one, thanks for the report

**Comment by ralphbean** [comment]
Np.. I'm working on the fix now.
