### ISSUE TITLE
500 error when trying to approve new test package in staging

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/packagedb-cli#91]
```bash
❯ pkgdb-admin --user ralph --pkgdburl https://admin.stg.fedoraproject.org/pkgdb --bzurl https://partner-bugzilla.redhat.com process 1457
To keep going, we need to authenticate against bugzilla at https://partner-bugzilla.redhat.com/xmlrpc.cgi
Bugzilla user: rbean@redhat.com
Bugzilla password: 
#1457 (Awaiting Review) - ralph requested the new package "modules/testmodule" on "master"
       review: https://bugzilla.redhat.com/12345
[+] Requester ralph is a packager
[-] The bug title does not fit the expected one
   exp: "Review Request: testmodule - A test module for modularity in stg" vs obs: "ps-to-printer.fpi"
[-] Wrong bug component 
   exp: "Package Review" vs obs: "rhs-printfilters"
[-] Wrong bug product 
   exp: "Fedora" vs obs: "Red Hat Linux"
[-] Non-packager shishz@alum.rpi.edu commented on review bug
[-] Non-packager notting@redhat.com commented on review bug
[-] Non-packager hotfix-tracker-xmlrpc@redhat.com commented on review bug
[-] Review bug created by `email shishz@alum.rpi.edu unknown to FAS` but request by ralph
[-] fedora-review flag has not been touched

What should we do about this requests?
approve, deny, pass: approve
FAS password for user ralph: 
FAS password for user ralph: 
Error: HTTPSConnectionPool(host='admin.stg.fedoraproject.org', port=443): Max retries exceeded with url: /pkgdb/api/admin/action/status (Caused by ResponseError('too many 500 error responses',))
ERROR:root:Generic error catched:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pkgdb2client/admin.py", line 519, in main
    arg.func(arg)
  File "/usr/lib/python2.7/site-packages/pkgdb2client/admin.py", line 461, in do_process
    data = __handle_request_package(actionid, action)
  File "/usr/lib/python2.7/site-packages/pkgdb2client/admin.py", line 325, in __handle_request_package
    'status': 'Approved'
  File "/usr/lib/python2.7/site-packages/pkgdb2client/__init__.py", line 211, in handle_api_call
    output = self.call_api(path, params, data)
  File "/usr/lib/python2.7/site-packages/pkgdb2client/__init__.py", line 192, in call_api
    data = self.send_request(url, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedora/client/openidbaseclient.py", line 240, in send_request
    output = func(method, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 435, in send
    raise RetryError(e, request=request)
RetryError: HTTPSConnectionPool(host='admin.stg.fedoraproject.org', port=443): Max retries exceeded with url: /pkgdb/api/admin/action/status (Caused by ResponseError('too many 500 error responses',))
```

I'll go look for logs on the server side next..

**Comment by ralphbean** [comment]
Could find any errors in the logs on the server side for this.

**Comment by pypingou** [comment]
the thing is that pkgdb API may be returning a 500 error just to say that the request was invalid, (yes it's unfortunate, pkgdb2 was one of the first API I wrote) so maybe try with --debug to see if we can get the entire response back?

**Comment by pypingou** [comment]
That's one down-side from this feature we added in the base client vs what we had in pkgdb-cli before :-s

**Comment by ralphbean** [comment]
I noticed that if I change ``retries=None`` in pkgdbclient's call to ``super().__init_(...)``, then it prints out the message nicely.

**Comment by pypingou** [comment]
\ó/ thanks for finding this one out :)
